### ISSUE TITLE
[xray] it is better to add the function that can select the correct version of caddy according to your CPU 

### ISSUE THREAD

**Issue by cary-sas** [mixool/across#4]
for the script in across's xray folder , as title, thank you
https://stackoverflow.com/questions/48678152/how-to-detect-386-amd64-arm-or-arm64-os-architecture-via-shell-bash

**Comment by mixool** [comment]
我自己常用的就debian 10 amd64  不准备适配其它的

**Comment by cary-sas** [comment]
我是用的ubuntu，然后装在oracle 的arm机器上。 其实你只要改一点点就行了

-- ***@***.***> 于2021年6月20日周日 下午3:24写道：
